# Generated by Django 4.1.1 on 2022-09-26 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='img',
            field=models.ImageField(default='g', upload_to='', verbose_name='Аватарка'),
        ),
    ]
