# Generated by Django 4.1.1 on 2022-10-04 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_customuser_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=25, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='img',
            field=models.ImageField(default='g', upload_to='', verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(max_length=25, verbose_name='Last name'),
        ),
    ]
