# Generated by Django 4.1.1 on 2022-10-05 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_customuser_first_name_alter_customuser_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='img',
            field=models.ImageField(default='user/default_avatar.png', upload_to='user/<django.db.models.fields.EmailField>/', verbose_name='Avatar'),
        ),
    ]
