# Generated by Django 4.1.1 on 2022-10-11 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_customuser_img_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='img',
            field=models.ImageField(default='user/default_avatar.png', upload_to='user/', verbose_name='Avatar'),
        ),
    ]
