# Generated by Django 4.1.1 on 2022-10-11 20:26

from django.db import migrations
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_customuser_email_alter_customuser_img'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', user.models.CustomUserManager()),
            ],
        ),
    ]
