# Generated by Django 4.1.1 on 2022-10-14 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='date of create user'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='user activity'),
        ),
    ]
