# Generated by Django 4.1.1 on 2022-10-17 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_remove_customuser_friends_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='img',
            field=models.ImageField(default='default_avatar.png', upload_to='user/<django.db.models.fields.EmailField>/', verbose_name='Avatar'),
        ),
    ]
