# Generated by Django 4.1.1 on 2022-10-18 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_customuser_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='img',
            field=models.ImageField(default='default_avatar.png', upload_to='', verbose_name='Avatar'),
        ),
    ]
